CREATE DATABASE IF NOT EXISTS mywebsite_admin DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mywebsite_admin;

CREATE TABLE IF NOT EXISTS admin_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS image_file (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  file_name VARCHAR(255) NOT NULL,
  url VARCHAR(1000) NOT NULL,
  oss_object_key VARCHAR(500) NOT NULL,
  content_type VARCHAR(100) DEFAULT NULL,
  file_size BIGINT DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS home_content (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  section_key VARCHAR(100) NOT NULL UNIQUE,
  content_json TEXT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS video_file (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  file_name VARCHAR(255) NOT NULL,
  url VARCHAR(1000) NOT NULL,
  oss_object_key VARCHAR(500) NOT NULL,
  content_type VARCHAR(100) DEFAULT NULL,
  file_size BIGINT DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 初始管理员账号会在应用启动时根据 application.yml 中的 app.admin 配置自动写入数据库。
